on:
  push:
    branches:
      - master

permissions:
  contents: write
  packages: write
  pull-requests: write

name: release-please
jobs:
  changelog:
    name: Generate Changelog
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.release.outputs.tag }}
      skipped: ${{ steps.changelog.outputs.skipped }}
      changelog: ${{ steps.changelog.outputs.changelog }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GIT_TOKEN }}
          
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - run:
          npm install conventional-changelog-conventionalcommits@7.0.2
          npm install conventional-recommended-bump@9.0.0
      
      - name: Create changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v5.2.1
        with:
          github-token: ${{ secrets.GIT_TOKEN }}
          pre-commit: ./.github/.pre-commit.js
          skip-version-file: true
          skip-git-pull: true
          pre-release: false
  
  release-please:
    runs-on: ubuntu-latest
    needs: changelog
    steps:
      - name: Release
        id: release
        if: ${{ needs.changelog.outputs.skipped != 'true' }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.changelog.outputs.tag }}
          body: ${{ needs.changelog.outputs.changelog }}
          files: dist/*

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        if: ${{ needs.changelog.outputs.skipped != 'true' }}
        with:
          version: 9

      # Setup .npmrc file to publish to npm
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'
        if: ${{ needs.changelog.outputs.skipped != 'true' }}

      - name: CI
        run: pnpm install --frozen-lockfile
        if: ${{ needs.changelog.outputs.skipped != 'true' }}

      - name: Build
        run: pnpm build
        if: ${{ needs.changelog.outputs.skipped != 'true' }}

      - name: Publish
        run: pnpm publish
        if: ${{ needs.changelog.outputs.skipped != 'true' }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
