name: Publish Release

on:
  push:
    branches:
      - master

permissions:
  contents: write
  packages: write
  pull-requests: write

jobs:
  changelog:
    name: Generate Changelog
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.changelog.outputs.tag }}
      skipped: ${{ steps.changelog.outputs.skipped }}
      changelog: ${{ steps.changelog.outputs.changelog }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GIT_TOKEN }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - run:
          pnpm install conventional-changelog-conventionalcommits@7.0.2
          pnpm install conventional-recommended-bump@9.0.0

      - name: Create changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v5.2.1
        with:
          github-token: ${{ secrets.GIT_TOKEN }}
          git-user-name: 'Search Dropdown Bot'
          git-user-email: 'admin@searchdropdown.com'
          config-file-path: ./.github/.config.cjs
          pre-commit: ./.github/.pre-commit.cjs
          skip-version-file: true
          skip-git-pull: true
          pre-release: false

  release:
    runs-on: ubuntu-latest
    needs: changelog
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GIT_TOKEN }}
      
      - name: Release
        id: release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.changelog.outputs.tag }}
          body: ${{ needs.changelog.outputs.changelog }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.6.0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: CI
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Publish
        run: pnpm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
